FROM python
RUN pip install flask
COPY ./templates /home/myapp/templates/
COPY exam.py /home/myapp/
EXPOSE 5050
CMD python /home/myapp/exam.py
FROM python
RUN pip install flask
COPY ./templates /home/myapp/templates/
COPY exam.py /home/myapp/
EXPOSE 5050
CMD python /home/myapp/exam.py
FROM python
RUN pip3 install flask
COPY ./templates /home/myapp/templates/
COPY exam.py /home/myapp/
EXPOSE 5050
CMD python /home/myapp/exam.py
FROM python
RUN pip3 install flask
COPY ./templates /home/myapp/templates/
COPY exam.py /home/myapp/
EXPOSE 5050
CMD python /home/myapp/exam.py
